### ISSUE TITLE
Step 3: Filter out genes that are more pLoF constrained than missense based on GNOMAD data

### ISSUE THREAD

**Issue by hoangthienan95** [corradin-lab/genetic-compensation#1]

**Comment by hoangthienan95** [comment]
Great Idea!

**Comment by brolosy** [comment]
Hi An,
As we discussed before the holidays, it would be useful to exclude the genes that are more constrained in nonsense mutations than missense.  I am attaching the file I mentioned.  There are 4 coloumns, the first is the gene name, 2nd is the observed/expressed (o/e) value of missense mutations in that gene, the 3rd is for o/e of predicted deleterious mutations and the 4th is for the LoF mutations (i.e. nonsense and splice variants).
The o/e values are a measure of constraint, the lower they are the more constrained the gene is.  Genes with values of 1 or higher are not constrained.  We generally consider lower than 0.75 as constrained to be more stringent.  But we want to exclude genes where the ratio of (o/e LOF over o/e misssense pphen) is less than 0.75 to avoid working with phenotypes that appear more in missense just because the LoF is deleterious.
[Constraints from gnomad 2.xlsx](https://github.com/corradin-lab/genetic-compensation/files/7842519/Constraints.from.gnomad.2.xlsx)

**Comment by hoangthienan95** [comment]
###683 genes do not have `oe_lof_div_oe_mis_pphen < 0.75`

![image](https://user-images.githubusercontent.com/25307953/150518922-ee688b39-f818-4739-a1a4-747b64370a90.png)


### We also don't have constraint data for 72 genes

![image](https://user-images.githubusercontent.com/25307953/150519153-9f41a2d4-917e-476d-90c9-8963a97617a9.png)

Result: only 384 genes left
